### ISSUE TITLE
Ditch choco enhanced exit codes tweak

### ISSUE THREAD

**Issue by nitzmahone** [mgmt-sa-tiger-team/skylight#15]
The tweak for enhanced exit codes should no longer be necessary. Chocolatey backed off on making that feature the default after they broke the world, and we've also released a fix to win_chocolatey so Ansible doesn't care (https://github.com/ansible/ansible/pull/53841, backported to 2.6 and 2.7 and released)

https://github.com/mgmt-sa-tiger-team/skylight/blob/master/roles/windows-workstation/tasks/main.yml#L11-L14

**Comment by oatakan** [comment]
Thanks @nitzmahone . I will test this and update.

**Comment by cigamit** [comment]
I tested this, it's still failing even after updating to 2.7.9.  Will leave our fix in for now until new Ansible rpms are pushed.  May even wait a few months after that, so that people don't immediately have to update their ansible install for the provisioner to still work (change control processes can take a while).

**Comment by cigamit** [comment]
This is resolved, we now check for the Ansible version to determine whether or not to set the exit codes.  In the future (~6 months) we will remove the task all together.
