### ISSUE TITLE
Ditch win_reboot and second call in windows-updates playbook

### ISSUE THREAD

**Issue by nitzmahone** [mgmt-sa-tiger-team/skylight#17]
In https://github.com/mgmt-sa-tiger-team/skylight/blob/master/windows-updates.yml, the `win_reboot` task and second call to `win_updates` is no longer necessary; just pass `reboot: yes` to `win_updates` and it will automatically batch updates and reboot as many times as needed.

Also update lab text in https://github.com/mgmt-sa-tiger-team/skylight/blob/master/docs/lab_guide/exercise7.adoc to reflect the reboot updates...

**Comment by oatakan** [comment]
Thanks @nitzmahone I will test this and update the issue.

**Comment by cigamit** [comment]
I am fine with ditching the win_reboot, as that was only there since we were at one time still supporting 2.4 at the time.  We can also remove the first win_update check.  The last call to win_update was so that I would see that more updates needed to be installed. On 2012, you find a lot of updates that don't show up until a preceding update is installed.  So it was basically just letting me know to run the playbooks again.  Guess I could instead do a loop on the actual update call until we have 0 left.

**Comment by cigamit** [comment]
The only bad thing about the current way I am doing it now, is that you can't see the list of updates that were installed, but that was never the point anyways.  It was to ensure that all updates were installed before a workshop.

We still need to rework Lesson 7, but its also not an active lesson at the moment (users can't see it in the list).

**Comment by oatakan** [comment]
Revised lesson 7 lab guide to use the reboot attribute and removed the win_reboot task:

**Comment by cigamit** [comment]
Thanks Orcun!

**Comment by cigamit** [comment]
Closing for now, feel free to reopen if you want to discuss any more changes to the Windows Updates playbooks / lessons.

**Comment by cigamit** [comment]
One issue I ran into, is that for some reason 'failed_update_count' isn't always returned even though it is marked as always on the docs page.

`until: update_result.found_update_count == 0 or update_result.failed_update_count == update_result.found_update_count`

**Comment by cigamit** [comment]
Removed failed_update_count for now.  Can revisit later if necessary
